- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  tags: [nginx, install]

- name: Cek apakah file virtual host sudah ada
  ansible.builtin.stat:
    path: /etc/nginx/sites-available/{{ domain }}.conf
  register: vhost_stat  

- name: Salin konfigurasi virtual host nginx (jika belum ada)
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-available/{{ domain }}.conf
    owner: root
    group: root
    mode: '0644'
  when: not vhost_stat.stat.exists
  tags: [nginx, config]

- name: Cek apakah symlink sudah benar
  ansible.builtin.stat:
    path: /etc/nginx/sites-enabled/{{ domain }}.conf
    follow: false
  register: vhost_symlink_stat

- name: Aktifkan virtual host dengan membuat symlink jika belum ada atau salah
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ domain }}.conf
    state: link
    force: true
  when: vhost_symlink_stat.stat.islnk is not defined or
        vhost_symlink_stat.stat.lnk_source != "/etc/nginx/sites-available/{{ domain }}.conf"
  notify: restart_nginx
  tags: [nginx, config]