- name: Setup Database Server (MariaDB)
  hosts: db
  become: true
  roles:
    - role: mariadb

- name: Setup Web Server (PHP, Nginx, SSL, WordPress)
  hosts: web
  become: true
  roles:
    - role: php
    - role: nginx
    - role: certbot
    - role: wordpress