- name: Install MariaDB Server
  ansible.builtin.apt: 
    name:
      - mariadb-server
      - python3-mysqldb
    state: present
    update_cache: yes
  tags: [mariadb, install]

- name: Aktifkan MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  tags: [mariadb, service]

- name: Set bind-address untuk remote access
  ansible.builtin.replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address\s*=.*$'
    replace: 'bind-address = {{ ip_dbsrv }}'
  notify: restart_mariadb
  tags: [mariadb, config]

- name: Membuat Database
  community.mysql.mysql_db:
    name: '{{ mysql_db }}'
    state: present
  tags: [mariadb, db]

- name: Membuat User
  community.mysql.mysql_user:
    name: '{{ mysql_user }}'
    password: '{{ mysql_password }}'
    priv: '{{ mysql_db }}.*:ALL'
    host: '{{ ip_websrv }}'
    state: present
  tags: [mariadb, user]