- name: Install Certbot
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes
  tags: [certbot, install]

- name: Tambahkan cron job untuk certbot renew
  ansible.builtin.cron:
    name: "Perbarui sertifikat SSL dengan certbot"
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "*"
    job: "cd /usr/bin && ./certbot renew"
    user: root
  tags: [certbot, cron]

- name: Cek apakah sertifikat SSL sudah ada
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  register: certbot_cert
  tags: [certbot, ssl]    

- name: Install SSL cert
  ansible.builtin.command: >
    certbot --non-interactive
            -m {{ email }}
            --agree-tos
            --no-eff-email
            --nginx
            -d {{ domain }}
            --redirect
  args:
    creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  when: not certbot_cert.stat.exists
  tags: [certbot, ssl]